-- Lists all privileges of the MySQL users user_0d_1 and user_0d_2
REVOKE IF EXISTS AUDIT_ABORT_EXEMPT, AUTHENTICATION_POLICY_ADMIN, FIREWALL_EXEMPT, GROUP_REPLICATION_STREAM, PASSWORDLESS_USER_ADMIN, SENSITIVE_VARIABLES_OBSERVER, TELEMETRY_LOG_ADMIN ON *.* FROM 'user_0d_1'@'localhost' IGNORE UNKNOWN USER;
-- Removes the same newer privileges from the second user
REVOKE IF EXISTS AUDIT_ABORT_EXEMPT, AUTHENTICATION_POLICY_ADMIN, FIREWALL_EXEMPT, GROUP_REPLICATION_STREAM, PASSWORDLESS_USER_ADMIN, SENSITIVE_VARIABLES_OBSERVER, TELEMETRY_LOG_ADMIN ON *.* FROM 'user_0d_2'@'localhost' IGNORE UNKNOWN USER;
-- Shows the grants of user_0d_1
SHOW GRANTS FOR 'user_0d_1'@'localhost';
-- Shows the grants of user_0d_2
SHOW GRANTS FOR 'user_0d_2'@'localhost';
